# suppress inspection "UnusedProperty" for whole file
# Increase the memory available to gradle
org.gradle.jvmargs=-Xmx4G

# General properties
supported_versions=26.3
curse_project=465066
modrinth_project=X5dUUm4k
minecraft_version=26.3

# Mod properties
mod_version=15.0.0
maven_group=be.florens
archives_name=expandability

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.3.0.26-beta
