modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/florensie/expandability/issues"
license = "MIT"

[[mods]]
modId = "expandability"
version = "${version}"
displayName = "ExpandAbility"
authors = "Florens, Wouter"
description = '''
Library mod that provides increased control over vanilla abilities
'''
logoFile = "icon.png"

[[mixins]]
config = 'expandability-common.mixins.json'
[[mixins]]
config = 'expandability.mixins.json'

[[dependencies.expandability]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.expandability]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"
