modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "expandabilitytest"
version = "1.0.0"
displayName = "ExpandAbility Test"
authors = "Florens"
description = '''
Test mod for ExpandAbility
'''

[[mixins]]
config = 'expandability-testmod-common.mixins.json'

[[dependencies.expandabilitytest]]
modId = "expandability"
required = true
ordering = "NONE"
side = "BOTH"
versionRange = "[0,)" # fuck you froge
